name: C compilation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-And-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make
      
    - name: Run test
      run: make test
